[general]
library_name = "libpio"
output_file_path = "./libpiolib_api.jl"
jll_pkg_name = "PIOLib_jll"
export_symbol_prefixes = ["pio_"]
epilogue_file_path = "./epilogue.jl"

output_ignorelist = [
    "PIO_ORIGIN_ANY",
    "PIO_ORIGIN_INVALID",
    "pio0",
    "pio_error",
    "pio_get_error",
    "pio_clear_error",
    "pio_enable_fatal_errors",
    "pio_get_sm_count",
    "pio_get_instruction_count",
    "pio_get_fifo_depth",
    "check_pio_param",
    "check_gpio_param",
    "pio_sm_config_xfer",
    "pio_sm_xfer_data",
    "pio_can_add_program",
    "pio_can_add_program_at_offset",
    "pio_add_program",
    "pio_add_program_at_offset",
    "pio_remove_program",
    "pio_clear_instruction_memory",
    "pio_encode_delay",
    "pio_encode_sideset",
    "pio_encode_sideset_opt",
    "pio_encode_jmp",
    "pio_encode_jmp_not_x",
    "pio_encode_jmp_x_dec",
    "pio_encode_jmp_not_y",
    "pio_encode_jmp_y_dec",
    "pio_encode_jmp_x_ne_y",
    "pio_encode_jmp_pin",
    "pio_encode_jmp_not_osre",
    "pio_encode_wait_gpio",
    "pio_encode_wait_pin",
    "pio_encode_wait_irq",
    "pio_encode_in",
    "pio_encode_out",
    "pio_encode_push",
    "pio_encode_pull",
    "pio_encode_mov",
    "pio_encode_mov_not",
    "pio_encode_mov_reverse",
    "pio_encode_irq_set",
    "pio_encode_irq_wait",
    "pio_encode_irq_clear",
    "pio_encode_set",
    "pio_encode_nop",
    "pio_sm_claim",
    "pio_claim_sm_mask",
    "pio_sm_unclaim",
    "pio_claim_unused_sm",
    "pio_sm_is_claimed",
    "pio_sm_init",
    "pio_sm_set_config",
    "pio_sm_exec",
    "pio_sm_exec_wait_blocking",
    "pio_sm_clear_fifos",
    "pio_sm_set_clkdiv_int_frac",
    "pio_sm_set_clkdiv",
    "pio_sm_set_pins",
    "pio_sm_set_pins_with_mask",
    "pio_sm_set_pindirs_with_mask",
    "pio_sm_set_consecutive_pindirs",
    "pio_sm_set_enabled",
    "pio_set_sm_mask_enabled",
    "pio_sm_restart",
    "pio_restart_sm_mask",
    "pio_sm_clkdiv_restart",
    "pio_clkdiv_restart_sm_mask",
    "pio_enable_sm_in_sync_mask",
    "pio_sm_set_dmactrl",
    "pio_sm_is_rx_fifo_empty",
    "pio_sm_is_rx_fifo_full",
    "pio_sm_get_rx_fifo_level",
    "pio_sm_is_tx_fifo_empty",
    "pio_sm_is_tx_fifo_full",
    "pio_sm_get_tx_fifo_level",
    "pio_sm_drain_tx_fifo",
    "pio_sm_put",
    "pio_sm_put_blocking",
    "pio_sm_get",
    "pio_sm_get_blocking",
    "pio_get_default_sm_config_for_pio",
    "pio_get_default_sm_config",
    "sm_config_set_out_pins",
    "sm_config_set_set_pins",
    "sm_config_set_in_pins",
    "sm_config_set_sideset_pins",
    "sm_config_set_sideset",
    "sm_config_set_clkdiv_int_frac",
    "sm_config_set_clkdiv",
    "sm_config_set_wrap",
    "sm_config_set_jmp_pin",
    "sm_config_set_in_shift",
    "sm_config_set_out_shift",
    "sm_config_set_fifo_join",
    "sm_config_set_out_special",
    "sm_config_set_mov_status",
    "pio_gpio_init",
    "clock_get_hz",
    "gpio_init",
    "gpio_set_function",
    "gpio_set_pulls",
    "gpio_set_outover",
    "gpio_set_inover",
    "gpio_set_oeover",
    "gpio_set_input_enabled",
    "gpio_set_drive_strength",
    "gpio_pull_up",
    "gpio_pull_down",
    "gpio_disable_pulls",
    "stdio_init_all",
    "sleep_ms",
]
